### ISSUE TITLE
2 different `data.table`-related errors

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.project#34]
I hit two separate `data.table` errors when running the example below.
Please note that I am trying to create the project from scratch. This is, I opened a clean RStudio session, _outside_ of any project and am using `setupProject` to create the project folder structure and import modules.

```
Require::Require(c("PredictiveEcology/LandR@development",
                   "CeresBarros/SpaDES.project@misc-fixes",
                   "terra"))

out <- setupProject(name = "LandRDemo_vegOnly",
                    options = list("reproducible.useTerra" = TRUE),
                    paths = list(projectPath = "D:/GitHub/LandR-tutorials/LandRDemo_coreVeg",
                                 modulePath = "D:/GitHub/LandR-tutorials/LandRDemo_coreVeg/modules",
                                 scratchPath = tempdir(),
                                 packagePath = "D:/GitHub/LandR-tutorials/packages"),
                    modules = c("PredictiveEcology/Biomass_speciesData@terra-migration",
                                "PredictiveEcology/Biomass_borealDataPrep@terra-migration",
                                "PredictiveEcology/Biomass_speciesParameters@development",
                                "PredictiveEcology/Biomass_core@terra-migration",
                                "PredictiveEcology/Biomass_validationKNN@development")
)
```

The first error was happened during the internal `getModule` call, on line 115 (`rbindlist` failed)
```
Item 2 has 10 columns, inconsistent with item 1 which has 11 columns. To fill missing columns use fill=TRUE
```

When I tried running again to `debug(getModule)`  I got:
```
setting up paths ...
Setting:
  options(
    reproducible.cachePath = 'D:/GitHub/LandR-tutorials/LandRDemo_coreVeg/cache'
    spades.inputPath = 'D:/GitHub/LandR-tutorials/LandRDemo_coreVeg/inputs'
    spades.outputPath = 'D:/GitHub/LandR-tutorials/LandRDemo_coreVeg/outputs'
    spades.modulePath = 'D:/GitHub/LandR-tutorials/LandRDemo_coreVeg/modules'
    spades.scratchPath = 'C:/Users/cbarros/AppData/Local/Temp/Rtmp04wFjH'
  )
  done setting up paths
Error in packageVersion(dai, lib.loc = .libPaths()[1]) : 
  there is no package called ‘data.table’
```

**Comment by CeresBarros** [comment]
I traced down the second error to the fact that `packagePath` is `"D:/GitHub/LandR-tutorials/packages"` but, internally, `.libPaths()[1]` becomes `"D:/GitHub/LandR-tutorials/packages/4.3"`. The later is, of course more appropriate, but is not the path that 1) the user specifies and 2) or that `setupProject` uses to place the packages -- I see them being places in `packagePath` not `.libPaths()[1]`

**Comment by eliotmcintire** [comment]
A couple things:

1. `setupProject` is intended to be "first" not after packages are loaded. The chances are VERY high that this will not work because you installed and loaded `LandR` from your personal folder, then switched package directory then you will try to find `LandR` and it won't be there. Put all packages **inside** the `setupProject`.

This is the reason you had problems with `data.table` ... you installed and loaded `LandR` from one place, then loaded it, then you tried to deal with package dependencies within `setupProject`. Just remove your first line of `Require`, it is unnecessary. If you need to have a line for `SpaDES.project` installation, then you must just install it manually. Restart R. In general, it is hard to work on packages whose job it is to install the same packages.

So --> this is an unusual problem that you are trying to develop content within `SpaDES.project`, but you did not do it in a way that doesn't prevent you from creating problems. 


2. `name` is not the same as `basename(paths$projectPath)`; this warning will have been shown. You must have them be the same. `SpaDES.project` overrides "Name" with the `basename(paths$projectPath)`, but gives the warning.

3. Your code did not create the same errors you had, so I couldn't address them directly. Suffice, they should disappear if you do above steps.

```
Require::Install("PredictiveEcology/SpaDES.project@windowsTesting")

out <- setupProject(name = "LandRDemo_vegOnly",
                    options = list("reproducible.useTerra" = TRUE),
                    paths = list(projectPath = "C:/GitHub/LandR-tutorials/LandRDemo_coreVeg",
                                 modulePath = "C:/GitHub/LandR-tutorials/LandRDemo_coreVeg/modules",
                                 scratchPath = tempdir(),
                                 packagePath = "C:/GitHub/LandR-tutorials/packages"),
                    modules = c("PredictiveEcology/Biomass_speciesData@terra-migration",
                                "PredictiveEcology/Biomass_borealDataPrep@terra-migration",
                                "PredictiveEcology/Biomass_speciesParameters@development",
                                "PredictiveEcology/Biomass_core@terra-migration",
                                "PredictiveEcology/Biomass_validationKNN@development"),
                    packages = c("PredictiveEcology/LandR@development",
                                 "terra")
)
```

**Comment by eliotmcintire** [comment]
Please see `windowsTesting` branch for other fixes that are relevant that this example does not hit... but it will.

**Comment by eliotmcintire** [comment]
FWIW, the replacement code above worked perfectly with the new branch (`windowsTesting`)

**Comment by CeresBarros** [comment]
Indeed, I've tested it myself and only found a wee browser that needed removing see #36

**Comment by CeresBarros** [comment]
on this note:
> name is not the same as basename(paths$projectPath); this warning will have been shown. You must have them be the same. SpaDES.project overrides "Name" with the basename(paths$projectPath), but gives the warning.

oops, that was my bad, they were supposed to be the same!
