### ISSUE TITLE
don't use package subdir within the project dir?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#5]
Because Rstudio a) actively monitors all files withn the project directory for changes, and b) insists on searching the packages subdir when trying to do quick find of files (e.g., using `Ctrl + .`), there are performance issues when a large number of packages are being used with a project.

WORKAROUND:
Use a project-specific package directory, but place it outside the project directory.

How do `packrat`/`renv` avoid this?

See: https://github.com/rstudio/rstudio/issues/1984

**Comment by achubaty** [comment]
@eliotmcintire from comment in the issue likend above:

> I had success setting files to ignore with the `file_monitor_ignored_components` setting in [rstudio-prefs.json](https://docs.rstudio.com/ide/server-pro/latest/session-user-settings.html).

This seems to be working...I've added the following, but note this is _user_ level setting, not project level.

```
    "file_monitor_ignored_components": [
        "data/",
        "inputs/",
        "packages/"
    ]
```

**Comment by eliotmcintire** [comment]
I is not quite a *user* level setting, sadly. It is a *user session* level setting. So, it has to be reset for every project.

**Comment by achubaty** [comment]
Not true. If it's not sticking, you likely missed a comma or something in the prefs list. It's persisting across sessions for me.

**Comment by eliotmcintire** [comment]
"session" means "project". So if you start a new project, you have to reset this. It must be in the project folder.

**Comment by achubaty** [comment]
No, it persists across sessions and projects. This is a user level setting. I’ll post screen shots showing how to set it.

**Comment by achubaty** [comment]
![B0E733F8-0E04-44B0-B88D-10C25A557745](https://user-images.githubusercontent.com/3435577/118143728-e44cc680-b3c8-11eb-96b1-c025b35da864.jpeg)

Go to ‘Help’ menu, under ‘Diagnostics’ is ‘Edit User Prefs File’.

**Comment by achubaty** [comment]
Alternatively, if you are on Linux, edit `~/.config/rstudio/rstudio-prefs.json` directly.

**Comment by eliotmcintire** [comment]
Either this does not work on Windows, or I am unable to follow instructions. Either way, this mechanism is either difficult or not viable as a means of a Windows machine to avoid monitoring every file in the packages folder. In a new project, please allow the packages folder to be outside the Rstudio project.

**Comment by achubaty** [comment]
I've confirmed it does work on Windows.

You _can_ use another directory. Simply update it in `.Rprofile`, and possibly the top of `00-global.R`.

But I will add an argument to allow passing a custom package directory.

**Comment by eliotmcintire** [comment]
Why is it in `.Rprofile`?  How did that get there?

**Comment by achubaty** [comment]
That's the mechanism to set the lib paths when the project is opened. It's the same mechanism as `packrat`/`renv`.

**Comment by eliotmcintire** [comment]
Since I don't use those 2 packages (they have never worked when I tried them, plus they took a long time to set up), I cannot report whether Rstudio becomes unresponsive due to those packages. If those packages do make RStudio unresponsive, then lets not copy that! If they don't make RStudio unresponsive, then we have to figure out how they do it.

**Comment by achubaty** [comment]
per the links above: they have hardcoded exclusions in the Rstudio source code. But the prefs.json workaround does work.

**Comment by eliotmcintire** [comment]
Since this is not a simple workaround (i.e., you have to understand `json` language a little bit, find a hidden folder, find an editor that works reliably -- the Rstudio one that opens when I follow the photo above is very buggy and doesn't show keystrokes on my machines, and make no syntax errors or else the changes are wiped with no error message) , I think it is very important that the default package location _not_ be inside the package, unless there is way for the `SpaDES.project` to change the `prefs.json` file. I believe it is not sensible to create an unresponsive Rstudio environment by default.

**Comment by achubaty** [comment]
I agree that Rstudio's behaviour is obnoxious in this regard.

So what would be a good default location? `<projectName>_packages/` in the project's parent directory?

I'll implement this to start and we can see how it goes.
